### PR TITLE
added post endpoint api/messages

### PR DESCRIPTION
**Pull request by STEP0HEN**
# Description

Please provide a short summary explaining what this PR is about.

Post endpoint to api/messages.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by tpetrina — CHANGES_REQUESTED** [review]
Looks good, but many files were changed that shouldn't have been. Please fix.

**Review by bytewiz — APPROVED** [review]
Looks good to me 👍

**Review by tpetrina — CHANGES_REQUESTED** [review]
If you could remove package.json and package-lock.json changes, that would be awesome.
Also, file src/server/api/routes/messages-router.js is unnecessarily changed.

**Review by tpetrina — APPROVED** [review]
Good work!

**Review by benna100 — APPROVED** [review]

**Pull request merged**
