### PR TITLE
add head nave to channel and fix relevantes issues

### PR DESCRIPTION
**Pull request by wael85**
# Description

- fix channels-controller to add imageUrl to the response
- fix channelInfo contanier to return channel title and image or other member name and profileImage
-fix channelInformation component style for the image
- fix the forward url on info button in channelheadNav component
- edit channel.js controler to desplay the headnav

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by wael85** [comment]
@panivita  I know you already did this but there is many changes has to be done in other files to achieve all function works
please lock at this pr and lets talk

**Comment by benna100** [comment]
Merge conflict. There are also error in the static code analysis about an import for something. Try ask lucy about this. We had the same problem with her but fixed it

**Comment by panivita** [comment]
Hi Wael. I don't know why you change all code in channel.js, but all this functionality work good, I don't know what is the reason to change it, because your task is doing functionality for the information button, when click it is should open a new page this channel information. Why you change return, now we have duplication of code.

**Comment by benna100** [comment]
This looks like what Victoria worked on!? The channel header is already in develop

**Pull request closed without merging**
