### PR TITLE
User profile

### PR DESCRIPTION
**Pull request by panivita**
# Description

Add user profile details. 
Add styling. Add fontawesome icons (changes in package-json)
Add default value for user profile image and username. 

Fixes # (issue)

# How to test?
in storybook

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by benna100 — CHANGES_REQUESTED** [review]
Looks super good victoria!

Please setup the routing for the `/profile` url. Remember to add it to the general navigation aswell.

**Comment by panivita** [comment]
Hi Benjamin. thank for review. In navigationHeader and in app.js we have route and link to profile. In which file I should add routing?

**Comment by benna100** [comment]
> 
> 
> Hi Benjamin. thank for review. In navigationHeader and in app.js we have route and link to profile. In which file I should add routing?
> I add font-awesome to project. That why we have merge conflict. Can we save these changes?

Ahh i did not know that the route was already added. If it is there, then fine :) 

Yes i know its because of the fonts, but jst merge develop (newest version) into your branch, run npm install and then add, commit and push the package-lock file

**Review by benna100 — APPROVED** [review]

**Comment by benna100** [comment]
Victoria you have some error with the checks. Its with the naming.

**Pull request merged**
